codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "100...100"

  status:
    project:
      default:
        target: 100%
        threshold: 0%
        if_ci_failed: error
        informational: false

    patch:
      default:
        target: 100%
        threshold: 0%
        if_ci_failed: error
        informational: false

    changes:
      default:
        target: 100%
        threshold: 0%
        if_ci_failed: error
        informational: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "**/*_test.go"
  - "test/"
  - "hack/"
  - "bin/"
  - ".github/"
  - "**/zz_generated.*.go"

flags:
  unittests:
    paths:
      - "api/"
      - "controllers/"
      - "internal/"
      - "cmd/"
    carryforward: true
