name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - mikelane

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Deploy operator with '...'
        2. Create PreviewEnvironment CR with '...'
        3. Observe error '...'
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell

  - type: input
    id: version
    attributes:
      label: Previewd Version
      description: What version of Previewd are you running?
      placeholder: "v0.1.0"
    validations:
      required: true

  - type: input
    id: k8s-version
    attributes:
      label: Kubernetes Version
      description: What version of Kubernetes are you using?
      placeholder: "v1.31.0"
    validations:
      required: true

  - type: dropdown
    id: install-method
    attributes:
      label: Installation Method
      description: How did you install Previewd?
      options:
        - Helm
        - kubectl apply
        - Kustomize
        - Other
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here, such as screenshots, configuration files, etc.
